name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Update to the latest version as per official documentation

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20

   
